---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-pvc
  namespace: esphome
  labels:
    app.name: esphome
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi