apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: home-assistant-svc
  name: home-assistant-codeserver
  namespace: home-assistant
  labels:
    app.kubernetes.io/instance: home-assistant
    app.kubernetes.io/name: home-assistant
spec:
  ports:
    - name: codeserver
      protocol: TCP
      port: 12321
      targetPort: codeserver
 selector:
#    app.kubernetes.io/name: codeserver
    app.kubernetes.io/instance: home-assistant
    app.kubernetes.io/name: home-assistant
  type: LoadBalancer
  loadBalancerIP: 192.168.42.19
