---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-codeserver
  namespace: home-assistant
  annotations:
    metallb.universe.tf/allow-shared-ip: home-assistant-svc
  labels:
    app.kubernetes.io/instance: home-assistant
    app.kubernetes.io/name: home-assistant
spec:
  ports:
    - name: codeserver
      port: 12321
      targetPort: 12321
 selector:
    app.kubernetes.io/instance: home-assistant
    app.kubernetes.io/name: home-assistant
  type: LoadBalancer
  loadBalancerIP: 192.168.42.19
