apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: home-assistant-svc
#    metallb.universe.tf/address-pool: server
  name: esphome-tcp
  namespace: home-assistant
spec:
  ports:
    - name: esphome
      port: {{ .Values.esphome.service.port }}
      targetPort: {{ .Values.esphome.service.port }}
    - name: esphome-api
      port: 6053
      targetPort: 6053
  selector:
    app.kubernetes.io/name: esphome
  type: LoadBalancer
  loadBalancerIP: 192.168.42.19
