apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: home-assistant-svc
    metallb.universe.tf/address-pool: server
  name: esphome-tcp
  namespace: home-assistant
spec:
  ports:
    - name: http
      port: {{ .Values.esphome.service.port }}
      targetPort: {{ .Values.esphome.service.port }}
  selector:
    app.kubernetes.io/name: esphome
  type: LoadBalancer
  loadBalancerIP: 192.168.42.19
