{{- if .Values.appdaemon.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: null
  annotations: null
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: home-assistant
    app.kubernetes.io/name: appdaemon
  name: home-assistant-appdaemon
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: primary
      app.kubernetes.io/instance: home-assistant
      app.kubernetes.io/name: appdaemon
  template:
    metadata:
      annotations: null
      labels:
        app.kubernetes.io/component: primary
        app.kubernetes.io/instance: home-assistant
        app.kubernetes.io/name: appdaemon
    spec:
        containers:
            - env:
              - name: "HA_URL"
                value: "http://192.168.42.19:8123/"
              - name: "HA_TOKEN"
                value: ""
              image: acockburn/appdaemon:latest
              name: appdaemon
              imagePullPolicy: {{ .Values.appdaemon.image.pullPolicy }}
              ports:
              - name: appdaemon
                containerPort: {{ .Values.appdaemon.service.port }}
                protocol: TCP
              volumeMounts:
              - mountPath: /apps
                name: appdaemon-pvc
                subPath: appdaemon
              - mountPath: /conf
                subPath: appdaemon
                name: appdaemon-pvc
        restartPolicy: Always
        volumes:
            - name: appdaemon-pvc
              persistentVolumeClaim:
                claimName: homeassistant-pvc
{{- end }}

