apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-configmap
  namespace: home-assistant
data:
  database_url: home-assistant
  homeassistant_ip: 192.168.1.1
  ingress_hostname: homeassistant.domain.my
