apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-postgresql
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: home-assistant
    app.kubernetes.io/name: postgresql
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle:  home-assistant-postgresql
  claimRef:
    kind: PersistentVolumeClaim
    namespace: home-assistant
    name: data-home-assistant-postgresql-0