apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: server
  name: homeassistant-tcp
  namespace: homeassistant
spec:
  ports:
    - name: http
      port: 8123
      targetPort: 8123
      protocol: TCP
  selector:
    app.kubernetes.io/name: home-assistant
  type: LoadBalancer
  loadBalancerIP: 192.168.42.19
