---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: home-assistant
spec:
  storageClassName: longhorn-static
  volumeName: ha-postgresql
  volumeMode: Block
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-home-assistant-postgresql-0
  namespace: home-assistant
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: home-assistant
    app.kubernetes.io/name: postgresql
spec:
  storageClassName: longhorn-static
  volumeName: home-assistant-postgresql
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi