
image:
  repository: acockburn/appdaemon
  tag: 4.2.1
persistence:
  config:
     enabled: true
     existingClaim: home-assistant-pvc
     mountPath: ""
     subPath:
       - path: .
         mountPath: /ha-conf
       - path: appdaemon
         mountPath: /conf
env:
  TZ: Europe/Berlin
  HA_URL: http://192.168.42.19:8123/
  TOKEN:  cthvYFGgpS482SyvbPnddw0XoJRRoVfgQzTco93A3Xw
  DASH_URL: http://192.168.42.19:5050/

service:
  main:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: 192.168.42.19
    port: 5050
    nodePort: 5050
    ports:
      http:
        port: 5050
