apiVersion: v2
name: home-assistant
description: Home Assistant
version: 1.0.0
appVersion: 2022.5.2
dependencies:
  - name: home-assistant
    repository: https://k8s-at-home.com/charts/
    version: 13.1.2