apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-red-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle:  node-red-pv
  claimRef:
    kind: PersistentVolumeClaim
    namespace: node-red
    name: node-red-bloc