apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
  labels:
    io.kompose.service: node-red
  name: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node-red
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
      labels:
        io.kompose.network/node-red-net: "true"
        io.kompose.service: node-red
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/Berlin
          image: nodered/node-red:latest
          name: node-red
          ports:
            - containerPort: 1880
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: node-red-pvc
      restartPolicy: Always
      volumes:
        - name: node-red-pvc
          persistentVolumeClaim:
            claimName: node-red-pvc
