---
image:
  repository: nodered/node-red
  tag: 2.1.4
  pullPolicy: IfNotPresent

# -- environment variables. See [image docs](https://nodered.org/docs/getting-started/docker) for more details.
env:
  # -- "Europe/Berlin" the container timezone
  TZ: "Europe/Berlin"
#  NODE_OPTIONS:
  NODE_RED_ENABLE_PROJECTS: "true"
  NODE_RED_ENABLE_SAFE_MODE: "false"
  FLOWS: flows.json

# -- Configures service settings for the chart.
service:
  main:
    type: LoadBalancer
    port: 1880
    nodePort: 1880
    loadBalancerIP: 192.168.42.9
    ports:
      http:
        port: 1880

hostAliases:
 - ip: "192.168.42.9"
   hostnames:
   - node-red.thomitzek.net

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
persistence:
  data:
    enabled: true
    existingClaim: node-red-pvc
#    mountPath: /data

podAnnotations:
  backup.velero.io/backup-volumes: data