apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zwave2mqtt
spec:
  rules:
    - host: zwave.thomitzek.net
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
              name: zwave2mqtt
              port: http