apiVersion: v1
kind: Service
metadata:
  name: zwave2mqtt-tcp
  namespace: zwave2mqtt
  annotations:
    metallb.universe.tf/allow-shared-ip: server
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: websocket
      port: 3030
      targetPort: 3030
      protocol: TCP
  selector:
    name: zwave2mqtt
  type: LoadBalancer
  loadBalancerIP: 192.168.42.26