apiVersion: v1
kind: Service
metadata:
  labels:
    name: zwave2mqtt-tcp
    io.ebt.service: zwave2mqtt-tcp
  name: zwave2mqtt-tcp
  namespace: zwave2mqtt
  annotations:
#    metallb.universe.tf/address-pool: server
    metallb.universe.tf/allow-shared-ip: zwave2mqtt
spec:
#  externalIPs:
#    - 192.168.42.18
  ports:
#    - port: 80
#      targetPort: 80
#      protocol: TCP
#      name: http
    - port: 3030
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
#    app.kubernetes.io/name: zwave2mqtt
#    io.ebt.service: zwave2mqtt
    name: zwave2mqtt
  type: LoadBalancer
  loadBalancerIP: 192.168.42.26