---
apiVersion: v1
kind: Service
metadata:
  name: zwave2mqtt
  labels:
    app: zwave2mqtt
    name: zwave2mqtt
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/name: zwave2mqtt
#    name: zwave2mqtt
