---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zwave-pvc
  namespace: zwave2mqtt
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zwave2mqtt-pvc
  namespace: zwave2mqtt
  labels:
    app.name: zwave2mqtt
spec:
  storageClassName: longhorn-static
  volumeName: zwave-pv
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi