apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: diyhue-pvc
  name: diyhue-pvc
  namespace: diyhue
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
