apiVersion: v1
kind: Service
metadata:
  labels:
    metallb.universe.tf/address-pool: server
    metallb.universe.tf/allow-shared-ip: diyhue-svc
    io.kompose.service: diyhue
  name: diyhue
  namespace: diyhue
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 80
    - name: "https"
      port: 443
      targetPort: 443
  selector:
    io.kompose.service: diyhue
  type: NodePort
  externalIPs:
    - 192.168.42.26
#  type: LoadBalancer
#  loadBalancerIP: 192.168.42.26
