---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multipan-pvc
  namespace: multipan
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multipan-app
  namespace: multipan
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
