apiVersion: v1
kind: Service
metadata:
  name: multipan-udp
  namespace: multipan
  labels:
      app.kubernetes.io/instance: multipan
      app.kubernetes.io/name: multipan-udp
  annotations:
#    metallb.universe.tf/address-pool: server
    metallb.universe.tf/allow-shared-ip: multipan
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: "9999"
      protocol: TCP
      port: 9999
      targetPort: 9999
    - name: "8080"
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: "8086"
      protocol: TCP
      port: 8086
      targetPort: 8086
  selector:
#    name: multipan
    app.kubernetes.io/instance: multipan
    app.kubernetes.io/name: multipan
  type: LoadBalancer
  loadBalancerIP: 192.168.42.27
  externalIPs:
    - 192.168.42.27
  ipFamilies:
    - IPv4