apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/instance: zwave-js-ui
    name: zwave-tcp
  name: zwave-tcp
  namespace: zwave
subsets:
#  - addresses:
#      - targetRef:
#          app.kubernetes.io/instance: zwave-js-ui
#          kind: Pod
#          namespace: zwave
#        ip: 192.168.42.28
  - ports:
      - name: websocket
        port: 3030
        protocol: TCP
      - name: http
        port: 8091
        protocol: TCP