image:
  repository: esphome/esphome
  pullPolicy: IfNotPresent
  tag: 2022.5.0

env:
  ESPHOME_DASHBOARD_USE_PING: true
  # ESPHOME_DASHBOARD_RELATIVE_URL: "/"
  # ESPHOME_QUICKWIZARD:
  # ESPHOME_IS_HASSIO:
  # DISABLE_HA_AUTHENTICATION:
  # USERNAME:
  # PASSWORD:
service:
  main:
    ports:
      http:
        port: 6052

ingress:
  main:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/target: thomitzek.net
#      cert-manager.io/cluster-issuer: letsencrypt-production
#      nginx.ingress.kubernetes.io/auth-url: https://auth.${DOMAIN}/oauth2/auth
#      nginx.ingress.kubernetes.io/auth-signin: https://auth.${DOMAIN}/oauth2/start
#      hajimari.io/enable: "true"
#      hajimari.io/icon: chip
    hosts:
      - host: esphome.thomitzek.net
        paths:
          - path: /
            pathType: Prefix
 #   tls:
 #     - hosts:
 #         - *host
 #       secretName: esphome-tls
persistence:
  config:
    enabled: true
    existingClaim: esphome-pvc
resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 1
    memory: 1Gi