apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appdaemon
  namespace: argocd
spec:
  project: home

  source:
    repoURL: https://github.com/Thro42/k3s-home-ops.git
    targetRevision: HEAD
    path: cluster/appdaemon
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: HOME_ASSISTANT_IP
          value: '192.168.42.19'
        - name: HOME_ASSISTANT_TOKEN
          value: 

  destination: 
    server: https://kubernetes.default.svc
    namespace: home-assistant

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
