apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calibre-web-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Thro42/k3s-home-ops.git
    targetRevision: HEAD
    path: cluster/calibre-web
    helm:
      releaseName: calibre-web
      valueFiles:
        - "values.yaml"

  destination: 
    server: https://kubernetes.default.svc
    namespace: calibre-web

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
