apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: esphome
  namespace: argocd
spec:
  project: home

  source:
    repoURL: https://github.com/Thro42/k3s-home-ops.git
    targetRevision: HEAD
    path: cluster/esphome
    helm:
      releaseName: esphome
      valueFiles:
        - "values.yaml"

  destination: 
    server: https://kubernetes.default.svc
    namespace: esphome

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
