apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: habridge-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Thro42/k3s-home-ops.git
    targetRevision: HEAD
    path: cluster/habridge
  destination: 
    server: https://kubernetes.default.svc
    namespace: habridge

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
