apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-postgresql
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle:  home-assistant-postgresql
  claimRef:
    kind: PersistentVolumeClaim
    namespace: home-assistant
    name: data-home-assistant-postgresql-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ha-postgresql
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle: ha-postgresql
  claimRef:
    kind: PersistentVolumeClaim
    namespace: home-assistant
    name: postgresql-pvc
---
