apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-helm
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Thro42/k3s-home-ops.git
    targetRevision: HEAD
    path: cluster/longhorn-helm
    helm:
      releaseName: longhorn
      valueFiles:
        - "values.yaml"

  destination: 
    server: https://kubernetes.default.svc
    namespace: longhorn-system

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
