apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosquitto-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: http://git.thomitzek.net:3000/thro42/home-ops.git
    targetRevision: HEAD
    path: cluster/mosquitto
  destination: 
    server: https://kubernetes.default.svc
    namespace: mosquitto

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
