apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosquitto-app
  namespace: argocd
spec:
  project: home-iot
  source:
    repoURL: https://github.com/Thro42/k3s-home-ops.git
    targetRevision: HEAD
    path: cluster/mosquitto
  destination: 
    server: https://kubernetes.default.svc
    namespace: mosquitto
  ignoreDifferences:
    - group: apps
      kind: ConfigMap
      jsonPointers:
      - /data/mosquitto.conf
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    automated:
      selfHeal: true
      prune: true
