apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multipan
  namespace: argocd
spec:
  project: home-iot

  source:
    repoURL: https://github.com/Thro42/k3s-home-ops.git
    targetRevision: HEAD
    path: cluster/multipan
  destination: 
    server: https://kubernetes.default.svc
    namespace: multipan

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    automated:
      selfHeal: true
      prune: true
