apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Thro42/k3s-home-ops.git
    targetRevision: HEAD
    path: cluster/nfs-provisioner
    helm:
      releaseName: nfs-provisioner
      valueFiles:
        - "values.yaml"

  destination: 
    server: https://kubernetes.default.svc
    namespace: nas-storage

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
