apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
spec:
  destination:
    name: 'rook-ceph'
    namespace: rook-ceph
    server: 'https://kubernetes.default.svc'
  source:
    path: cluster/rook-ceph
    repoURL: 'https://github.com/Thro42/k3s-home-ops.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true