apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zigbee2mqtt
  namespace: argocd
spec:
  project: home-iot

  source:
    repoURL: https://github.com/Thro42/k3s-home-ops.git
    targetRevision: HEAD
    path: cluster/zigbee2mqtt
  destination: 
    server: https://kubernetes.default.svc
    namespace: zigbee2mqtt
  ignoreDifferences:
    - group: apps
      kind: ConfigMap
      jsonPointers:
      - /app/configuration.yaml

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    automated:
      selfHeal: true
      prune: true
