apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zwave-js-ui
  namespace: argocd
spec:
  project: home-iot

  source:
    repoURL: https://github.com/Thro42/k3s-home-ops.git
    targetRevision: HEAD
    path: cluster/zwave-js-ui
  destination: 
    server: https://kubernetes.default.svc
    namespace: zwave

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    automated:
      selfHeal: true
      prune: true