apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
    app.kubernetes.io/name: pihole-dnsmasq
    app.kubernetes.io/instance: pihole
  labels:
     net.ebt.app: piihole
  name: pihole-dnsmasq
  namespace: pihole
data:
  01-pihole.conf: ""
  02-custom.conf: ""
  05-pihole-custom-cname.conf: ""
  06-rfc6761.conf: ""