---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-remote-pv
spec:
  storageClassName: nfs-storage-class
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.42.4
    path: "/volume1/docker/pihole"
