apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    net.ebt.service: pihole-pvc
  name: pihole-pvc
spec:
  storageClassName: nfs-nas
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
