---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc
spec:
  storageClassName: nfs-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  pihole-dnsm-pvc
spec:
  storageClassName: nfs-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
 