apiVersion: batch/v1
kind: CronJob
metadata:
  name: copy-to-remote
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pihole-to-remote
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            args: ['cp /etc/pihole/custom.list /mnt/pihole_remote/pihole-configs/custom.list']
            volumeMounts:
            - name: pihole-pvc
              mountPath: /etc/pihole
            - name: pihole-remote-pvc
              mountPath: /mnt/pihole_remote
          restartPolicy: OnFailure
          volumes:
            - name: pihole-pvc
              readOnly: true
              persistentVolumeClaim:
                claimName: pihole-pvc
            - name: pihole-remote-pvc
              persistentVolumeClaim:
                claimName: pihole-remote-pvc
