apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    net.ebt.service: pihole-pvc
  name: pihole-pvc
spec:
  storageClassName: longhorn-static
  volumeName: pihole-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
