apiVersion: batch/v1
kind: CronJob
metadata:
  name: copy-to-remote
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pihole-to-remote
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - cp /etc/pihole/custom.list /mnt/pihole_remote/pihole-configs/custom.list 
          restartPolicy: OnFailure
