apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-remote-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
      storageClassName: nfs-storage-class