apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-remote-pvc
spec:
  storageClassName: nfs-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
 