apiVersion: v1
kind: Service
metadata:
  labels:
    net.ebt.service: pihole
  name: pihole
  annotations:
    metallb.universe.tf/address-pool: pihole
    metallb.universe.tf/allow-shared-ip: pihole-svc
spec:
  ports:
    - name: 53-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: "67"
      port: 67
      protocol: UDP
      targetPort: 67
  selector:
    net.ebt.service: pihole
  type: LoadBalancer
  loadBalancerIP: 192.168.42.6
  