apiVersion: v1
kind: Service
metadata:
  labels:
    net.ebt.service: pihole
  name: pihole
spec:
  ports:
    - name: "53"
      port: 53
      targetPort: 53
    - name: 53-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: "67"
      port: 67
      protocol: UDP
      targetPort: 67
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    net.ebt.service: pihole
  type: LoadBalancer
  loadBalancerIP: 192.168.42.6
  