apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: calibre-web

resources:
- values.yaml

patches:
- target:
    kind: port
    name: port
  patch: |-
    - op: replace
    path: /spec/ports/port
    value: 8888