resources:
- values.yaml

patches:
- target:
    kind: port
    name: port
  patch: |-
    - op: replace
    path: /service/main/ports/http/port
    value: 8888

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization