---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  labels:
    app.kubernetes.io/name: zigbee2mqtt
    app: zigbee2mqtt
    name: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zigbee2mqtt
        app: zigbee2mqtt
    spec:
      containers:
      - name: zigbee2mqtt
        image: koenkk/zigbee2mqtt:1.26.0
        imagePullPolicy: IfNotPresent
        env:
          - name: TZ
            value: Europe/Berlin
          - name: "ZIGBEE2MQTT_DATA"
            value: "/data"
          - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER # optional - can also be configured in the configuration.yaml in the configmap
            value: "mqtt://192.168.42.10"
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
        resources: 
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 2
            memory: 2Gi
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          - name: websocket
            containerPort: 8888
            protocol: TCP
        volumeMounts:
          - name: zigbee2mqtt-data
            mountPath: /data
          - name: zigbee2mqtt-config
            mountPath: /app/configuration.yaml
            subPath: configuration.yaml
          - name: zigbee2mqtt-udev
            mountPath: /run/udev
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 0
          failureThreshold: 6
          timeoutSeconds: 2
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 0
          failureThreshold: 6
          timeoutSeconds: 2
          periodSeconds: 10
        startupProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 0
          failureThreshold: 30
          timeoutSeconds: 2
          periodSeconds: 5
      volumes:
        - name: zigbee2mqtt-data
          persistentVolumeClaim:
            claimName: zigbee-pvc
        - name: zigbee2mqtt-udev
          hostPath:
            path: /run/udev
        - name: zigbee2mqtt-config
          configMap:
            name: zigbee2mqtt-config