apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle:  zigbee-pv
  claimRef:
    kind: PersistentVolumeClaim
    namespace: zigbee2mqtt
    name: zigbee-pv