apiVersion: v1
data:
  subnet.conf: |
    "subnet4":
    [
     {
      "subnet": "192.168.42.0/24",
      "pools": [
       {
        "pool": "192.168.42.60-192.168.42.254"
       }
      ],
      "relay": {
       "ip-address": "192.168.42.11"
      },
      "option-data": [
       {
        "name": "routers",
        "data": "192.168.42.11"
       }
      ]
     }
    ]
kind: ConfigMap
metadata:
  name: keasubnet
  namespace: dhcp
