apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cert-manager
spec:
  rules:
    - host: cert-manager.thomitzek.net
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: cert-manager-webhook
              port: 
                number: 443