kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-nfs-storage-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-storage-provisioner
    # replace with namespace where provisioner is deployed
    namespace: default
roleRef:
  kind: ClusterRole
  name: nfs-storage-provisioner-runner
  apiGroup: rbac.authorization.k8s.io