apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    compare-options: IgnoreExtraneous,IgnoreDifference=mosquitto.conf
    sync-options: Prune=false
  labels:
     net.ebt.app: mosquitto
  name: mosquitto-configmap
  namespace: mosquitto
data:
  mosquitto.conf: |-