apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: longhorn-static
  volumeName: mosquitto-pv
  resources:
    requests:
      storage: 8Gi