apiVersion: v1
kind: Service
metadata:
  labels:
    net.ebt.service: mosquitto
  name: mosquitto
spec:
  ports:
    - name: "1883"
      port: 1883
      targetPort: 1883
    - name: "9001"
      port: 9001
      targetPort: 9001
  selector:
     net.ebt.service: mosquitto
