apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.42.6/32
  - 192.168.42.17-192.168.42.35
  - 192.168.43.100-192.168.43.200
  autoAssign: true
  avoidBuggyIPs: false
