apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-nas-provisioner
  labels:
    app: nfs-nas-provisioner
  # replace with namespace where provisioner is deployed
#  namespace: default
  namespace: nas-storage
  annotations:
   nfs.io/createUID: "1001"
   nfs.io/createGID: "1001"
   nfs.io/createMode: "0755"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-nas-provisioner
  template:
    metadata:
      labels:
        app: nfs-nas-provisioner
    spec:
      affinity: 
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - {key: "node-role.kubernetes.io/storage", operator: In, values: ["true"]}
      serviceAccountName: nfs-nas-provisioner
      containers:
        - name: nfs-nas-provisioner
          image: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.16
          volumeMounts:
            - name: nfs-nas-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: k8s-sigs.io/nfs-subdir-external-provisioner
            - name: NFS_SERVER
              value: 192.168.42.4
            - name: NFS_PATH
              value: /volume1/cluster
            - name: UID
              value: 1001
            - name: GID
              value: 1001
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: "1"
              memory: 400Mi
      volumes:
        - name: nfs-nas-root
          nfs:
            server: 192.168.42.4
            path: /volume1/cluster
